Added continents.
drager/faker pull request #8
Opened 2019-04-09 15:23 UTC by marvinIsSacul

I added continents.

2019-04-09 17:30 UTC, drager requested changes
Thank you so much for this!

I added some comments that needs to be resolved. Also, consider running `dartfmt` on the code.

2019-04-09 17:30 UTC, drager commented on lib/src/data/address/continents.dart
> +  'South Ameria',
```suggestion
  'South America',
```

2019-04-09 17:30 UTC, drager commented on test/specs/address.dart
> +      expect(faker.address.neighborhood(), matches(new RegExp(r'^[\w\s]*$')));
This test looks like it's calling the wrong function.

2019-04-09 17:30 UTC, drager commented on lib/src/address.dart
> +  ///   faker.address.countryCode();
Please update the doc comments.

2019-04-09 18:05 UTC, marvinIsSacul commented
Oh, sorry. I didn't notice those errors. 

But I've fixed them now. Thanks.

2019-05-01 14:04 UTC, drager approved these changes
Thanks @marvinIsSacul! This looks great!

2019-05-01 14:05 UTC, merged

2019-05-01 18:21 UTC, marvinIsSacul commented
Thanks.